import { difficulties, Student, therapy } from ".prisma/client";
import prisma from "../../services/database"; // Relative path required, aliases throw error using seed

// Seed student data
const students: Student[] = [
    {
        id: 1,
        parentId: 4,
        firstName: "Jo",
        lastName: "Black",
        dateOfBirth: new Date(2010, 1),
        addressLine1: "999 Philips Street",
        addressLine2: null,
        postalCode: "M2L 3K4",
        cityName: "Waterloo",
        province: "ON",
        school: "SDC Public School",
        grade: 6,
        difficulties: [difficulties.SENSORY],
        otherDifficulties: null,
        therapy: [therapy.PHYSIO],
        otherTherapy: null,
        specialEducation: true,
        guardianExpectations: null,
        medication: null,
        allergies: null,
        additionalInfo: null,
        emergFirstName: "Rickson",
        emergLastName: "Yang",
        emergNumber: "1111111111",
        emergRelationToStudent: "Guardian",
        createdAt: new Date(),
        updatedAt: null,
    },
    {
        id: 2,
        parentId: 4,
        firstName: "Arianna",
        lastName: "Simmons",
        dateOfBirth: new Date(2015, 2),
        addressLine1: "999 Philips Street",
        addressLine2: null,
        postalCode: "M2L 3K4",
        cityName: "Waterloo",
        province: "ON",
        school: "SDC Public School",
        grade: 6,
        difficulties: [difficulties.SENSORY],
        otherDifficulties: null,
        therapy: [therapy.PHYSIO],
        otherTherapy: null,
        specialEducation: true,
        guardianExpectations: null,
        medication: null,
        allergies: null,
        additionalInfo: null,
        emergFirstName: "Rickson",
        emergLastName: "Yang",
        emergNumber: "1111111111",
        emergRelationToStudent: "Guardian",
        createdAt: new Date(),
        updatedAt: null,
    },
    {
        id: 3,
        parentId: 6,
        firstName: "Sahib",
        lastName: "Gould",
        dateOfBirth: new Date(2010, 1),
        addressLine1: "999 Philips Street",
        addressLine2: null,
        postalCode: "M2L 3K4",
        cityName: "Waterloo",
        province: "ON",
        school: "SDC Public School",
        grade: 6,
        difficulties: [difficulties.SENSORY],
        otherDifficulties: null,
        therapy: [therapy.PHYSIO],
        otherTherapy: null,
        specialEducation: true,
        guardianExpectations: null,
        medication: null,
        allergies: null,
        additionalInfo: null,
        emergFirstName: "Rebecca",
        emergLastName: "Ma",
        emergNumber: "1111111111",
        emergRelationToStudent: "Guardian",
        createdAt: new Date(),
        updatedAt: null,
    },
    {
        id: 4,
        parentId: 6,
        firstName: "Toni",
        lastName: "Dixon",
        dateOfBirth: new Date(2015, 2),
        addressLine1: "999 Philips Street",
        addressLine2: null,
        postalCode: "M2L 3K4",
        cityName: "Waterloo",
        province: "ON",
        school: "SDC Public School",
        grade: 6,
        difficulties: [difficulties.SENSORY],
        otherDifficulties: null,
        therapy: [therapy.PHYSIO],
        otherTherapy: null,
        specialEducation: true,
        guardianExpectations: null,
        medication: null,
        allergies: null,
        additionalInfo: null,
        emergFirstName: "Rebecca",
        emergLastName: "Ma",
        emergNumber: "1111111111",
        emergRelationToStudent: "Guardian",
        createdAt: new Date(),
        updatedAt: null,
    },
    {
        id: 5,
        parentId: 8,
        firstName: "Caris",
        lastName: "Aguilar",
        dateOfBirth: new Date(2010, 1),
        addressLine1: "999 Philips Street",
        addressLine2: null,
        postalCode: "M2L 3K4",
        cityName: "Waterloo",
        province: "ON",
        school: "SDC Public School",
        grade: 6,
        difficulties: [difficulties.SENSORY],
        otherDifficulties: null,
        therapy: [therapy.PHYSIO],
        otherTherapy: null,
        specialEducation: true,
        guardianExpectations: null,
        medication: null,
        allergies: null,
        additionalInfo: null,
        emergFirstName: "Vedant",
        emergLastName: "Patel",
        emergNumber: "1111111111",
        emergRelationToStudent: "Guardian",
        createdAt: new Date(),
        updatedAt: null,
    },
    {
        id: 6,
        parentId: 8,
        firstName: "Aman",
        lastName: "Riggs",
        dateOfBirth: new Date(2015, 2),
        addressLine1: "999 Philips Street",
        addressLine2: null,
        postalCode: "M2L 3K4",
        cityName: "Waterloo",
        province: "ON",
        school: "SDC Public School",
        grade: 6,
        difficulties: [difficulties.SENSORY],
        otherDifficulties: null,
        therapy: [therapy.PHYSIO],
        otherTherapy: null,
        specialEducation: true,
        guardianExpectations: null,
        medication: null,
        allergies: null,
        additionalInfo: null,
        emergFirstName: "Vedant",
        emergLastName: "Patel",
        emergNumber: "1111111111",
        emergRelationToStudent: "Guardian",
        createdAt: new Date(),
        updatedAt: null,
    },
];

/**
 * Upsert students
 * @param data custom data to upsert
 */
export default async function studentUpsert(data?: Student[]): Promise<void> {
    for (const student of data || students) {
        const { id, updatedAt, ...rest } = student;
        await prisma.student
            .upsert({
                where: {
                    id,
                },
                update: rest,
                create: {
                    id,
                    updatedAt,
                    ...rest,
                },
            })
            .catch((err) => console.log(err));
    }
}
