name: ci-pr

on:
    pull_request:
        branches:
            - main
            - staging

jobs:
    ci-pr:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [14]

        steps:
            - name: Checkout
              uses: actions/checkout@main

            - name: Check modified files for Terraform
              id: modified-files
              uses: uwblueprint/social-diversity-for-children/.github/workflows/modified-files.yml@main
              with:
                  branch: $GITHUB_BASE_REF
                  expression: "terraform/*"

            - name: test
              run: echo "modified files ${{steps.modified-files.outputs.modified}}"

            - name: Setup node env
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: ${{ matrix.node }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node_modules
              uses: actions/cache@v2
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              run: yarn

            - name: Fetch target pr branch for diff
              run: git fetch origin $GITHUB_BASE_REF:refs/remotes/origin/$GITHUB_BASE_REF

            - name: Linting modified files Prettier
              id: prettier-pr
              run: yarn lint:prettier-modified-files
              continue-on-error: true

            - name: Linting modified files ESlint
              id: eslint-pr
              run: yarn lint:eslint-modified-files
              continue-on-error: true

            - name: Create linting comment on error
              if: steps.prettier-pr.outcome == 'failure' || steps.eslint-pr.outcome == 'failure'
              uses: actions/github-script@v5
              with:
                  script: |
                      const output = `#### Prettier status: \`${{ steps.prettier-pr.outcome }}\`
                      #### Eslint status: \`${{ steps.eslint-pr.outcome }}\``;

                      github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: output
                      });
                      core.setFailed('Linting errors. Please check prettier and eslint');

            - name: Build
              run: yarn build
