name: ci-push

on:
    push:
        branches:
            - main
            - staging

jobs:
    ci-push:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [14]
        outputs:
            env: ${{steps.env-staging.outputs.env}}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set environment based on branch
              id: env-staging
              run: |
                  if [[ $GITHUB_REF_NAME = "staging" ]]; then
                    echo "::set-output name=env::staging"
                    echo Environment set to 'staging'
                  elif [[ $GITHUB_REF_NAME = "main" ]]; then
                    echo "::set-output name=env::production"
                    echo Environment set to 'production'
                  else
                    echo '$GITHUB_REF_NAME' does not equal 'staging' or 'main'
                    exit 1
                  fi

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Cache node_modules
              uses: actions/cache@v2
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              run: yarn

            - name: Linting all Prettier on push
              run: yarn lint:prettier

            - name: Linting all ESlint on push
              run: yarn lint:eslint

            - name: Build
              run: yarn build

    terraform:
        needs: ci-push
        environment: ${{needs.ci-push.outputs.env}}
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./terraform/environments
        env:
            TF_VAR_zoom_class_link_value: ${{ secrets.ZOOM_CLASS_LINK_VALUE }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'
                cache: 'pip'
                cache-dependency-path: '**/requirements.txt'

            - name: Install Lambda dependencies
              run:  |
                cd ../../modules/lambda/files/cronMailing
                pip install -r requirements.txt -t .

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Terraform steps
              uses: uwblueprint/sdc-actions/actions/terraform-fmt-validate-plan-apply@main
              with:
                plan: false
                apply: true
