name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      bump:
        description: Semantic Version bump (major, minor, patch)
        required: true
      version-override:
        description: Version to use as an override (vx.x.x)
        required: false
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Initialize git config for PR author # https://github.com/actions/checkout/issues/13
      run: |
       git config user.name "github-actions[bot]"
       git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Get next semantic version
      if: github.event.inputs.version-override
      uses: uwblueprint/sdc-actions/actions/get-semantic-version@main
      with:
          bump:  ${{ github.event.inputs.bump }}
    # - name: Change version number and name
    #   run: printf 'ext.version_code = ${{ github.event.inputs.versionCode }}\next.version_name = "${{ github.event.inputs.versionName }}"\n' > app_versions.gradle
    # - name: Update Changelog
    #   uses: thomaseizinger/keep-a-changelog-new-release@v1
    #   with:
    #     version: ${{ github.event.inputs.versionName }}
    # - name: Commit changelog and manifest files
    #   id: make-commit
    #   run: |
    #     git add app_versions.gradle
    #     git add CHANGELOG.md
    #     git commit --message "Prepare release ${{ github.event.inputs.versionName }}"
    #     echo "::set-output name=commit::$(git rev-parse HEAD)"
    # - name: Push new branch
    #   run: git push origin release/v${{ github.event.inputs.versionName }}
    # - name: Create pull request into main
    #   uses: thomaseizinger/create-pull-request@1.0.0
    #   with:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    head: release/v${{ github.event.inputs.versionName }}
    #    base: main
    #    title: v${{ github.event.inputs.versionName }} into main
    #    reviewers: ${{ github.event.issue.user.login }}
    #    body: |
    #        Hi!
    #        This PR was created in response workflow running.
    #        I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
    # - name: Create pull request to develop
  
    #       body: |
    #           Hi!
    #           This PR was created in response workflow running.
    #           I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
