name: Tag Release drafter
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialize git config for PR author # https://github.com/actions/checkout/issues/13
      run: |
       git config user.name "github-actions[bot]"
       git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Get package.json version
      id: package
      uses: uwblueprint/sdc-actions/actions/get-package-version@main

    - name: Create tag
      run: git tag -a v${{steps.package.outputs.version}} -m "Automated tag v${{steps.package.outputs.version}} pushed by ${{github.actor}}"

    - name: Push tag
      run: git push origin v${{steps.package.outputs.version}}
    
    - name: Create draft release
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag: v${{steps.package.outputs.version}}
